neoforge_version=21.0.167
packs=hud-legacy,canvas-graphics,id-location,mobs-legacy,nbt-legacy,fuel-map,equip-legacy,shift-screen,profile-getter
label=1.21-1.21.1
range=[1.21,1.21.2)
neoforge_range=[21.0,21.2)
java=21
