neoforge_version=21.2.1-beta
packs=hud-legacy,canvas-graphics,id-location,mobs-legacy,nbt-legacy,fuel-values,equip-component,shift-screen,profile-getter
label=1.21.2-1.21.4
range=[1.21.2,1.21.5)
neoforge_range=[21.2,21.5)
java=21
