neoforge_version=21.9.16-beta
packs=hud-legacy,canvas-graphics,id-location,mobs-reference,nbt-or,fuel-values,equip-component,shift-client,profile-record
label=1.21.9-1.21.10
range=[1.21.9,1.21.11)
neoforge_range=[21.9,21.11)
java=21
