neoforge_version=21.6.20-beta
packs=hud-legacy,canvas-graphics,id-location,mobs-reference,nbt-or,fuel-values,equip-component,shift-screen,profile-getter
label=1.21.6-1.21.8
range=[1.21.6,1.21.9)
neoforge_range=[21.6,21.9)
java=21
