neoforge_version=21.7.25-beta
packs=hud-legacy,canvas-graphics,id-location,mobs-reference,nbt-or,fuel-values,equip-component,shift-screen,profile-getter,options-list,modifiers-holder,effects-holder,blockentity-modern,food-component,settings-screen,registries-builtin,text-components,harvest-tags,key-category-string
label=1.21.7
range=[1.21.7]
neoforge_range=[21.7,21.8)
java=21
