neoforge_version=21.11.45
packs=hud-legacy,canvas-graphics,id-identifier,mobs-modern,nbt-or,fuel-values,equip-component,shift-client,profile-record
label=1.21.11
range=[1.21.11]
neoforge_range=[21.11,21.12)
java=21
