neoforge_version=21.1.251
packs=hud-legacy,canvas-graphics,id-location,mobs-legacy,nbt-legacy,fuel-map,equip-legacy,shift-screen,profile-getter
label=1.21.1
range=[1.21.1]
neoforge_range=[21.1,21.2)
java=21
