neoforge_version=26.1.2.109
packs=hud-legacy,fuel-values,canvas-extractor,id-identifier,mobs-modern,nbt-or,equip-component,shift-client,profile-record,options-list,modifiers-holder,effects-holder,blockentity-modern,food-component,settings-screen,registries-builtin,text-components
label=26.1
range=[26.1,26.2)
neoforge_range=[26.1,26.2)
java=25
