neoforge_version=26.2.0.88
packs=hud-modern,fuel-values,canvas-extractor,id-identifier,mobs-modern,nbt-or,equip-component,shift-client,profile-record,options-list,modifiers-holder,effects-holder,blockentity-modern,food-component,settings-screen,registries-builtin,text-components,harvest-tags
label=26.2
range=[26.2,26.3)
neoforge_range=[26.2,26.3)
java=25
