neoforge_version=26.3.0.8-beta
packs=hud-modern,fuel-component,canvas-extractor,id-identifier,mobs-modern,nbt-or,equip-component,shift-client,profile-record
label=26.3
range=[26.3,26.4)
neoforge_range=[26.3,26.4)
java=25
