fabric_api_version=0.77.0+1.19.2
modmenu_version=4.1.2
packs=hud-legacy,canvas-1192,fabric-hud-callback-legacy,fabric-tooltip-legacy,id-constructor,mobs-1192,nbt-legacy,fuel-map,equip-1192,shift-screen,profile-getter,options-grid-1192,modifiers-legacy,effects-legacy,blockentity-1192,food-item,settings-screen-1192,registries-legacy,world-1192,text-components
label=1.19.2
range=1.19.2
java=17
gametest=false
loader_min=0.14.21
