fabric_api_version=0.83.0+1.20.1
modmenu_version=7.2.2
packs=hud-legacy,canvas-graphics,fabric-hud-callback-legacy,fabric-tooltip-legacy,id-constructor,mobs-legacy,nbt-legacy,fuel-map,equip-legacy,shift-screen,profile-getter,options-grid,modifiers-legacy,effects-legacy,blockentity-legacy,food-item,settings-screen,registries-builtin,world-options,text-components
label=1.20.1
range=1.20.1
java=17
gametest=false
loader_min=0.14.21
