fabric_api_version=0.141.6+1.21.11
modmenu_version=17.0.1-beta.1
packs=hud-legacy,canvas-graphics,fabric-hud-element,id-identifier,mobs-modern,nbt-or,fuel-values,equip-component,shift-client,profile-record
label=1.21.11
range=1.21.11
java=21
