fabric_api_version=0.116.17+1.21.1
modmenu_version=11.0.4
packs=hud-legacy,canvas-graphics,fabric-hud-callback,id-location,mobs-legacy,nbt-legacy,fuel-map,equip-legacy,shift-screen,profile-getter
label=1.21.1
range=1.21.1
java=21
gametest=false
