fabric_api_version=0.134.1+1.21.9
modmenu_version=16.0.1
packs=hud-legacy,canvas-graphics,fabric-hud-element,id-location,mobs-reference,nbt-or,fuel-values,equip-component,shift-client,profile-record
label=1.21.9-1.21.10
range=>=1.21.9 <1.21.11
java=21
