fabric_api_version=0.128.2+1.21.5
modmenu_version=14.0.2
packs=hud-legacy,canvas-graphics,fabric-hud-callback,id-location,mobs-reference,nbt-or,fuel-values,equip-component,shift-screen,profile-getter
label=1.21.5
range=1.21.5
java=21
