fabric_api_version=0.155.3+26.1.2
modmenu_version=18.0.1
packs=hud-legacy,fuel-values,canvas-extractor,fabric-hud-element,id-identifier,mobs-modern,nbt-or,equip-component,shift-client,profile-record
label=26.1-26.1.2
range=>=26.1 <26.2
java=25
