fabric_api_version=0.145.1+26.1
modmenu_version=18.0.1
packs=hud-legacy,fuel-values,canvas-extractor,fabric-hud-element,id-identifier,mobs-modern,nbt-or,equip-component,shift-client,profile-record,options-list,modifiers-holder,effects-holder,blockentity-modern,food-component,fabric-tooltip,settings-screen,registries-builtin,text-components,harvest-tags,key-category-identifier,keys-mapping
label=26.1-26.1.2
range=>=26.1 <26.2
java=25
