fabric_api_version=0.155.2+26.2
modmenu_version=20.0.1
packs=hud-modern,fuel-values,canvas-extractor,fabric-hud-element,id-identifier,mobs-modern,nbt-or,equip-component,shift-client,profile-record,options-list,modifiers-holder,effects-holder,blockentity-modern,food-component,fabric-tooltip,settings-screen,registries-builtin,text-components,harvest-tags
label=26.2
range=>=26.2 <26.3
java=25
