fabric_api_version=0.161.0+26.3
modmenu_version=20.0.1
packs=hud-modern,fuel-component,canvas-extractor,fabric-hud-element,id-identifier,mobs-modern,nbt-or,equip-component,shift-client,profile-record,options-list,modifiers-holder,effects-holder,blockentity-modern,food-component,fabric-tooltip,settings-screen,registries-builtin,text-components,harvest-tags,key-category-identifier,keys-mapping
label=26.3
range=>=26.3 <26.4
java=25
