forge_version=1.16.5-36.2.42
packs=hud-legacy,canvas-1192,id-constructor,mobs-116,nbt-legacy,fuel-forge,equip-116,shift-screen,profile-getter,options-grid-116,modifiers-legacy,effects-legacy,blockentity-116,food-item,settings-screen-1192,registries-legacy,world-116,text-components-118,forge-client-116,harvest-116
label=1.16.5
range=[1.16.5,1.17)
forge_range=[36,)
loader_range=[36,)
pack_format=6
java=8
main_excludes=
