forge_version=1.18.2-40.3.12
packs=hud-legacy,canvas-1192,id-constructor,mobs-1192,nbt-legacy,fuel-forge,equip-1192,shift-screen,profile-getter,options-grid-1192,modifiers-legacy,effects-legacy,blockentity-1192,food-item,settings-screen-1192,registries-legacy,world-118,text-components-118,forge-client-118,harvest-tags
label=1.18.2
range=[1.18.2,1.19)
forge_range=[40,)
loader_range=[40,)
pack_format=8
java=17
