forge_version=1.19.2-43.5.2
packs=hud-legacy,canvas-1192,id-constructor,mobs-1192,nbt-legacy,fuel-forge,equip-1192,shift-screen,profile-getter,options-grid-1192,modifiers-legacy,effects-legacy,blockentity-1192,food-item,settings-screen-1192,registries-legacy,world-1192,text-components,forge-client
label=1.19.2
range=[1.19.2,1.19.3)
forge_range=[43,)
loader_range=[43,)
pack_format=9
java=17
