forge_version=1.20.1-47.4.23
packs=hud-legacy,canvas-graphics,id-constructor,mobs-legacy,nbt-legacy,fuel-forge,equip-legacy,shift-screen,profile-getter,options-grid,modifiers-legacy,effects-legacy,blockentity-legacy,food-item,settings-screen,registries-builtin,world-options,text-components,forge-client,harvest-tags
label=1.20.1
range=[1.20.1,1.20.2)
forge_range=[47,)
java=17
loader_range=[47,)
pack_format=15
